### ISSUE TITLE
TypeError: data.split is not a function (in firefox when using Apache 2.3.x and later)

### ISSUE THREAD

**Issue by idgserpro** [Raptus/raptus.autocompletewidget#2]
@skaeser @wag

When it is used in archetypes as in [brasil.gov.vcge](https://github.com/plonegovbr/brasil.gov.vcge/blob/master/src/brasil/gov/vcge/at/extender.py#L39) and use Apache 2.3.x, occurs the js error: 

```
TypeError: data.split is not a function
```

in firefox in the content editing. This is because the [ajax call](https://github.com/Raptus/raptus.autocompletewidget/blob/master/raptus/autocompletewidget/widget.py#L131) returns None. The firefox considers this as an error (header content-type is not returned). [See](http://stackoverflow.com/questions/7642202/xml-parsing-error-not-well-formed-in-firefox-but-good-in-chrome). The method called by ajax is [this](https://github.com/Raptus/raptus.autocompletewidget/blob/master/raptus/autocompletewidget/widget.py#L45). He should return an not empty string instead of returning None. So one header content-type is returned.

@hvelarde  this is relating with https://github.com/Raptus/raptus.autocompletewidget/issues/1?

**Comment by hvelarde** [comment]
I really don't remember :-(

**Comment by idgserpro** [comment]
Changed title and description to indicate that the problem occurs in firefox when the Apache 2.3.x is used. [Apache 2.3.x does not add anymore the header 'content-type'](http://httpd.apache.org/docs/current/mod/core.html#defaulttype) when Zope didn't add.

@cmarangon you can help here?

@hvelarde @ericof this needs to be fixed because brasil.gov.vcge depends the raptus.autocompletewidget.
